const cartoons2 = [
    {
        imageUrl: '/src/assets/samples/e1-1.jpg',
        title: 'LV1 만화 1111111111111111111111111',
        authors: 'First Author',
        rating: 9.4,
        link: 'cartoon/2',
    },
    {
        imageUrl: '/src/assets/samples/e1-2.jpg',
        title: 'LV1 만화 2',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-3.jpg',
        title: 'LV1 만화 3',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-4.jpg',
        title: 'LV1 만화 4',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-5.jpg',
        title: 'LV1 만화 5',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-1.jpg',
        title: 'LV1 만화 1',
        authors: 'Second Author',
        rating: 9.4,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-2.jpg',
        title: 'LV1 만화 2',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-3.jpg',
        title: 'LV1 만화 3',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-4.jpg',
        title: 'LV1 만화 4',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-5.jpg',
        title: 'LV1 만화 5',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-1.jpg',
        title: 'LV1 만화 1',
        authors: 'Second Author',
        rating: 9.4,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-2.jpg',
        title: 'LV1 만화 2',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-3.jpg',
        title: 'LV1 만화 3',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-4.jpg',
        title: 'LV1 만화 4',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-5.jpg',
        title: 'LV1 만화 5',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-1.jpg',
        title: 'LV1 만화 1',
        authors: 'Second Author',
        rating: 9.4,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-2.jpg',
        title: 'LV1 만화 2',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-3.jpg',
        title: 'LV1 만화 3',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-4.jpg',
        title: 'LV1 만화 4',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-5.jpg',
        title: 'LV1 만화 5',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-1.jpg',
        title: 'LV1 만화 1',
        authors: 'Second Author',
        rating: 9.4,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-2.jpg',
        title: 'LV1 만화 2',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-3.jpg',
        title: 'LV1 만화 3',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-4.jpg',
        title: 'LV1 만화 4',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-5.jpg',
        title: 'LV1 만화 5',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-1.jpg',
        title: 'LV1 만화 1',
        authors: 'Second Author',
        rating: 9.4,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-2.jpg',
        title: 'LV1 만화 2',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-3.jpg',
        title: 'LV1 만화 3',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-4.jpg',
        title: 'LV1 만화 4',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },
    {
        imageUrl: '/src/assets/samples/e1-5.jpg',
        title: 'LV1 만화 5',
        authors: 'Second Author',
        rating: 8.7,
        link: 'https://comic.naver.com/webtoon',
    },



];

export default cartoons2;
